"use client";

import { useEffect, useState } from "react";
import { Bell, Settings } from "lucide-react";
import { radarRisks } from "@/lib/mock-data";
import type { ExtensionPage } from "@/lib/types";
import { ActionButton, LiveIndicator, MetricCard, ProgressBar, RadarPulse, SectionCard } from "../shared/UI";

export default function RadarPage({ onNavigate }: { onNavigate: (p: ExtensionPage) => void }) {
  const [stress, setStress] = useState(0);
  useEffect(() => { const id = window.setTimeout(() => setStress(78), 350); return () => window.clearTimeout(id); }, []);
  return <div className="page-frame page-enter"><header className="sidebar-header"><div className="header-row"><div style={{ display: "flex", alignItems: "center", gap: 9 }}><RadarPulse /><div><h1 className="header-title">QuantumRadar <span className="cyan">AI</span></h1><div className="header-subtitle">CRISIS FORECAST ENGINE</div></div></div><div style={{ display: "flex", alignItems: "center", gap: 7 }}><button className="nav-button" aria-label="Thông báo"><Bell size={15} /><i style={{ position: "absolute", right: 6, top: 6, width: 6, height: 6, borderRadius: "50%", background: "#ef4444" }} /></button><button className="nav-button" aria-label="Cài đặt"><Settings size={15} /></button><LiveIndicator /></div></div></header><div className="page-body">
    <section className="section-card" style={{ padding: 14, borderColor: "rgba(0,194,255,.3)", background: "linear-gradient(135deg,#071526,#0b1d32)", boxShadow: "0 0 22px rgba(0,194,255,.05)" }}><div className="row"><span className="eyebrow">Quantum Brief</span><RadarPulse /></div><div style={{ marginTop: 8, color: "#f0a25d", fontSize: 8.5, fontWeight: 700 }}>RỦI RO CHÍNH</div><h2 style={{ margin: "3px 0", fontFamily: "Outfit", fontSize: 21 }}>Liquidity Shock</h2><p style={{ margin: "0 0 11px", color: "#a8bacd", fontSize: 11 }}>AI phát hiện thanh khoản Curve đang suy yếu.</p><div className="metrics"><MetricCard value="72%" label="Khả năng xảy ra" tone="orange" /><MetricCard value="12-24h" label="Thời gian" /><MetricCard value="89%" label="Độ tin cậy AI" tone="cyan" /></div></section>
    <section><div className="row" style={{ marginBottom: 7 }}><div><h2 className="section-title" style={{ marginBottom: 1 }}>Crisis Radar</h2><div className="muted" style={{ fontSize: 9 }}>Emerging risks detected by QuantumRadar</div></div><span className="badge red">3 ACTIVE</span></div><div className="stack">{radarRisks.map((risk) => <SectionCard key={risk.id}><div className="row"><strong style={{ fontFamily: "Outfit", fontSize: 13 }}>{risk.title}</strong><span className={`badge ${risk.severity === "high" ? "orange" : risk.severity === "medium" ? "yellow" : "cyan"}`}>{risk.status}</span></div><div style={{ marginTop: 5 }}><strong className={`mono ${risk.severity === "high" ? "orange" : risk.severity === "medium" ? "yellow" : "cyan"}`}>{risk.probability}%</strong><span className="muted" style={{ fontSize: 10 }}> · {risk.horizon}</span></div></SectionCard>)}</div></section>
    <SectionCard><div className="row"><h2 className="section-title">Market Stress Index</h2><span className="badge orange">CAO</span></div><div style={{ marginBottom: 7 }}><strong className="mono orange" style={{ fontSize: 22 }}>{stress}</strong><span className="mono muted" style={{ fontSize: 10 }}> / 100</span></div><ProgressBar value={stress} /><div className="row muted" style={{ marginTop: 5, fontSize: 8 }}><span>Thấp</span><span>TB</span><span>Cao</span><span>Rất cao</span></div></SectionCard>
    <div className="stack"><ActionButton onClick={() => onNavigate("scenario")}>Xem Kịch Bản →</ActionButton><ActionButton variant="secondary" onClick={() => onNavigate("portfolio")}>Phân Tích Danh Mục</ActionButton><ActionButton variant="ghost" onClick={() => onNavigate("auto-protection")}>Bật Auto Protection</ActionButton></div>
  </div></div>;
}
